### ISSUE TITLE
ZONE attribute for multiple domains?

### ISSUE THREAD

**Issue by netwity** [smck83/expurgate-solo#1]
Hi there,

This is not an issue, but more of a question.

If I have to use your script and serve SPF records for multiple domains from a single server/docker instance, what should I use in 'ZONE' option in the docker command?

For example, lets say I've got domains mydomain.com, mydomain.net and mydomain.org. Am assuming I have to:

1. copy existing spf record to
_sd6sdyfn.mydomain.com
_sd6sdyfn.mydomain.net
_sd6sdyfn.mydomain.org

2. Run the command:

> docker run -t -p 9001:9001 -p 53:53/udp -e **ZONE=_spf** -e MY_DOMAINS="mydomain.com mydomain.net mydomain.org" -e SOURCE_PREFIX="_sd6sdyfn" --dns 1.1.1.1 --dns 8.8.8.8 smck83/expurgate-solo

3. Create a NS record pointing my server ip:
spf.ns.mydomain.net pointing to x.x.x.x

4. Change SPF record for each domain pointing to NS record
_spf.mydomain.com NS pointing to spf.ns.mydomain.net
_spf.mydomain.net NS pointing to spf.ns.mydomain.net
_spf.mydomain.org NS pointing to spf.ns.mydomain.net

Have I understood it correctly or do I need to make some changes to the 'ZONE' option in the docker command?

**Comment by smck83** [comment]
ZONE= is the root zone for the rblndsd DNS server and is a single hostname location of where you will host your rbldnsd/resolver container.

ZONE could be `_spf.mydomain.com` OR `_spf.mydomain.org` OR `abcdef.mydomain.net` or something completely different e.g. `myexpurgatehost.net`

Using _spf.mydomain.com as the example. You will create a single hostname per expurgate-solo instance, and point to the static IP, e.g. 

`expurgate.mydomain.com.          IN          A       192.0.2.1`

You will then point _spf.mydomain.com with type NS to the expurgate.mydomain.com hostname e.g.

`_spf.mydomain.com.         IN          NS         expurgate.mydomain.com.`

You will then point mydomain.com, mydomain.net and mydomain.org to the same place; `"v=spf1 include:%{ir}.%{d}._spf.mydomain.com ~all"` e.g.:
````
mydomain.com.      IN          TXT           "v=spf1 include:%{ir}.%{d}._spf.mydomain.com ~all"
mydomain.net.     IN          TXT           "v=spf1 include:%{ir}.%{d}._spf.mydomain.com ~all"
mydomain.org.      IN          TXT           "v=spf1 include:%{ir}.%{d}._spf.mydomain.com ~all"

````

**Comment by netwity** [comment]
Thanks for explaining.

It make sense. Instead of creating 3 different zones in my instance... I can simply combine existing SPF records of all three domains into one source, for example `_sd6sdyfn.mydomain.net` and then run your script, which will generate one root zone `_spf.mydomain.com` that can be used for all the three domains.

And since your scripts resolves the 10 record lookups issue and hides all the IP addresses, it does not matter how many mail sources/ip addresses you add under `_sd6sdyfn.mydomain.net`, it will continue to validate SPF lookups for all three domains. Amazing !!!

I'll go ahead and try it. And thanks for creating and maintaining this solution. It helps save us so much time and resources.

**Comment by smck83** [comment]
You will still create a subdomain per domain you are hosting. which gives you flexibility to not over-authorize IP addresses e.g.
````
_sd6sdyfn.mydomain.com.       IN      TXT   "v=spf1 ip4:192.0.2.1 ~all"
_sd6sdyfn.mydomain.net.       IN      TXT   "v=spf1 include:sendgrid.net ~all"
_sd6sdyfn.mydomain.org.       IN      TXT   "v=spf1 include:mailgun.org include:service-now.com ~all"

````

If you wanted to use a single one, you could set `MY_DOMAINS` to `mydomain.com` and configure:
````
_sd6sdyfn.mydomain.com.       IN     TXT "v=spf1 ip4:192.0.2.1 include:sengrid.net include:mailgun.org include:service-now.com ~all"
````

And then hard code the `%{d}` macro variable to mydomain.com e.g.

````
mydomain.com.      IN          TXT        "v=spf1 include:%{ir}.%{d}._spf.mydomain.com ~all"
mydomain.net.     IN          TXT           "v=spf1 include:%{ir}.mydomain.com._spf.mydomain.com ~all"
mydomain.org.      IN          TXT          "v=spf1 include:%{ir}.mydomain.com._spf.mydomain.com ~all"
````

**Comment by netwity** [comment]
Yup, will create subdomain for each domain.

Thank you :)

**Comment by smck83** [comment]
No worries, closing this off. Feel free to create another issue if you get stuck.
