### ISSUE TITLE
Will this run on ARM machines?

### ISSUE THREAD

**Issue by sujitph** [smck83/expurgate-solo#2]
First of all, thanks for your work. Instead of paying and subscribing to similar services, am using your Expurgate-Solo. It helped me save some money and sorted out my email delivery issues.

Will the docker images work on ARM VMs and RPi?

Thanks,

**Comment by smck83** [comment]
I'm glad to hear you found it useful. As is, I don't believe it would work on ARM processors.

The [Resolver script](https://raw.githubusercontent.com/smck83/expurgate-solo/main/config/resolver.py) would probably work as is on ARM using a docker ARM python docker container e.g., https://hub.docker.com/r/arm64v8/python/ but I haven't yet tested.

As for rbldnsd ; It appears this would be fairly straightforward using debian 
https://packages.debian.org/buster/arm64/rbldnsd/download
