### ISSUE TITLE
Multiple ZONE

### ISSUE THREAD

**Issue by lukasbeckerit** [smck83/expurgate-solo#3]
Hi.

I have a few domains and tried to create one NS entry on each DNS and put the SPF v=spf1 include:%{ir}.%{d}._spf.yourdomain.com -all, but the only one working is the one which I put in the ZONE setting. Is there any way to make the expurgate to respond to N domains instead of only one? My idea is each domain will use their own NS.

**Comment by smck83** [comment]
Expurgate operates under a single ZONE, and supports multiple DOMAINS under the zone.

e.g.
`MY_DOMAINS` is where you populate your 1 or many domains using space between each e.g. `mydomain1.com mydomain2.com sub.mydomain1.com`

`ZONE` is the DNS server which is 1 per instance of Expurgate.

i.e. everything operates under mydomain1.com to us %{ir}.%{d}._spf.zone.com where `_spf.zone.com` is populated in `ZONE`

If I understand correctly, you want

mydomain1.com to us %{ir}.%{d}._spf.zone1.com to be used for zone1.com and ir}.%{d}._spf.zone2.com to be used for zone2.com

What is the use case or reason for this? and Why won't multiple domains on 1 zone work ?

**Comment by lukasbeckerit** [comment]
Yes, you got it correct, I want to use:
mydomain1.com to us %{ir}.%{d}._spf.zone1.com to be used for zone1.com and ir}.%{d}._spf.zone2.com to be used for zone2.com
The reason why is I am a MSP and have multiple clients and they are unrelated. I would like to use their own domain on their SPF instead of a general one.

**Comment by smck83** [comment]
Why not use

Your domain, e.g. _spf.MSP-R-US.com as the zone and then all your spf across all customers are the same?


E.g. 

%{ir}.%{d}._spf.MSP-R-US.com 

Easier to support and monitor?

If you don't want to share `_spf.MSP-R-US.com` between customers and want to manage a ZONE (nameserver) per customer, you will need to host multiple version of Expurgate - 1 per domain (or customer) which would increase complexity in configuration and management. This comes down to how rbldnsd (DNS Server) runs; the environment variable ZONE is passed at runtime to rbldnsd into `zonename` below:

````
rbldnsd [options] zonename:type:fname,fname...
````
per https://rbldnsd.io/documentation/

**Comment by smck83** [comment]
It would fall outside scope of this project but if you were wanting to host multiple instances with different zones of expurgate behind a single IP on port 53, you could use dnsdist to redirect.

You may be able to do this with a single instance of expurgate with dnsdist in front doing modification in transit to the zone part.

While this could be a technical solution, I believe this would unnecessarily add complexity.

**Comment by lukasbeckerit** [comment]
Thank you for the explanation. I'll use one DNS for the NS zone for now. If you want to keep the suggestion for maybe a future version.
